### PR TITLE
allow DisableThrottlingAttribute on a class

### LINKED ISSUE #14: DisableThrottling on Class
Me again 😺 

The `DisableThrottlingAttribute` is checked at the Action level, but not on the Class.  Is there a reason for this?  We have some base classes that have it enabled and want to disable it on specific inherited classes.  ~If not, maybe mark that attribute as `Method` only?~ _Edit: can't do that with `ActionFilterAttribute` apparently_

I think the fix would be to `ThrottlingFilter.cs:352` [here](https://github.com/stefanprodan/MvcThrottle/blob/master/MvcThrottle/ThrottlingFilter.cs#L352):

```
            if (filterContext.ActionDescriptor.ControllerDescriptor.IsDefined(typeof(DisableThrottlingAttribute), true))
            {
                applyThrottling = false;
            }
```

I'd be happy to PR that if it helps.  

We just pushed this into production and are much <3

### PR DESCRIPTION
**Pull request by natelowry**
fixes #14

### CODE REVIEW

**Comment by natelowry** [comment]
hold on quick and i'll add to the example project 🍵

**Comment by natelowry** [comment]
alrighty!

**Comment by stefanprodan** [comment]
Looks great! thanks

**Comment by stefanprodan** [comment]
I've published v2.1.1, will be available once NuGet is done indexing.

Thanks again

**Pull request merged**
